// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type IRole struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

type IUser struct {
	ID    string `json:"id"`
	Name  string `json:"name"`
	Email string `json:"email"`
}
