package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.29

import (
	"context"
	"fmt"

	"github.com/alvaro84seis/gqlgen-todos/app/domain/entity"
	"github.com/alvaro84seis/gqlgen-todos/app/infrastructure/graph/generated"
	"github.com/alvaro84seis/gqlgen-todos/app/infrastructure/graph/model"
)

// Parent is the resolver for the parent field.
func (r *categoryResolver) Parent(ctx context.Context, obj *entity.Category) (*entity.Category, error) {
	filter := model.ICategoria{
		Code: &obj.ParentCode,
	}
	category, _ := r.GetCategoryByIDUseCase.GetCategoryByID(filter)
	return category, nil
}

// GetCategory is the resolver for the GetCategory field.
func (r *queryResolver) GetCategory(ctx context.Context, filter model.ICategoria) (*entity.Category, error) {
	category, _ := r.GetCategoryByIDUseCase.GetCategoryByID(filter)

	return category, nil
}

// Category returns generated.CategoryResolver implementation.
func (r *Resolver) Category() generated.CategoryResolver { return &categoryResolver{r} }

type categoryResolver struct{ *Resolver }

// !!! WARNING !!!
// The code below was going to be deleted when updating resolvers. It has been copied here so you have
// one last chance to move it out of harms way if you want. There are two reasons this happens:
//  - When renaming or deleting a resolver the old code will be put in here. You can safely delete
//    it when you're done.
//  - You have helper methods in this file. Move them out to keep these resolver files clean.
func (r *categoryResolver) ParentCode(ctx context.Context, obj *entity.Category) (string, error) {
	panic(fmt.Errorf("not implemented: ParentCode - parent_code"))
}
