package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.29

import (
	"context"
	"fmt"

	"github.com/alvaro84seis/gqlgen-todos/app/domain/entity"
	"github.com/alvaro84seis/gqlgen-todos/app/infrastructure/graph/model"
)

// SaveRole is the resolver for the saveRole field.
func (r *mutationResolver) SaveRole(ctx context.Context, input model.IRole) (string, error) {
	panic(fmt.Errorf("not implemented: SaveRole - saveRole"))
}

// GetRoles is the resolver for the GetRoles field.
func (r *queryResolver) GetRoles(ctx context.Context) ([]*entity.Role, error) {
	panic(fmt.Errorf("not implemented: GetRoles - GetRoles"))
}
