package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.29

import (
	"context"
	"fmt"

	"github.com/alvaro84seis/gqlgen-todos/app/domain/entity"
	"github.com/alvaro84seis/gqlgen-todos/app/infrastructure/graph/generated"
	"github.com/alvaro84seis/gqlgen-todos/app/infrastructure/graph/model"
	"github.com/labstack/gommon/log"
)

// Save is the resolver for the save field.
func (r *mutationResolver) Save(ctx context.Context, input model.IUser) (string, error) {
	panic(fmt.Errorf("not implemented: Save - save"))
}

// FindByID is the resolver for the FindByID field.
func (r *queryResolver) FindByID(ctx context.Context, id *string) ([]*entity.User, error) {
	user, err := r.GetUserByIDUseCase.GetUserByID(*id)

	return []*entity.User{user}, err
}

// Role is the resolver for the role field.
func (r *userResolver) Role(ctx context.Context, obj *entity.User) (*entity.Role, error) {
	log.Info(obj.ID)
	return &entity.Role{
		ID:   "1",
		Name: "Rol Uno",
	}, nil
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

// User returns generated.UserResolver implementation.
func (r *Resolver) User() generated.UserResolver { return &userResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type userResolver struct{ *Resolver }

// !!! WARNING !!!
// The code below was going to be deleted when updating resolvers. It has been copied here so you have
// one last chance to move it out of harms way if you want. There are two reasons this happens:
//  - When renaming or deleting a resolver the old code will be put in here. You can safely delete
//    it when you're done.
//  - You have helper methods in this file. Move them out to keep these resolver files clean.
func (r *userResolver) Descripcion(ctx context.Context, obj *entity.User) (string, error) {
	panic(fmt.Errorf("not implemented: Descripcion - descripcion"))
}
